OSEHRA-Sandbox/Product-Management

Visual/Documentation/README.rst
Visual/Documentation/howToSubmit.rst

Add a reStructuredText ocument which describes the process of
submitting a change to the ViViaN repository.  It goes through the
vivian-demo branch for public review and then ends with a pull request
to the master branch.

Add contribution documentation

---

Visual/index.php
Visual/pkg_interface_gen.py
Visual/pkgcsv_to_json.py

Update Index.php to support ICR interface.
Also update setup.py to set up the ICR interface.

Add ICR interface support.

---

Visual/Documentation/testing.rst
Visual/d3.treeview.js
Visual/test/CMakeLists.txt
Visual/test/test_index.py
Visual/test/test_menus.py

* More detailed error messages
* Commented out image compare test (for now)
* Improved reliability for index.php tests
* Updated testing documentation

Updated tests

---

Visual/test/test_installdep.py
Visual/test/test_installscale.py

Add a test for each of the install visualizations that were added to
ViViaN.

Add Selenium test for install visualizations

---

Visual/Documentation/GenerateData.rst

* Remove references to 'VistADataParse'
* Add ICR data generation

Update data generation documentation

---

Visual/test/test_links.py
Visual/vivian_osehra_image.php

This contains links to all interfaces.

Add a new top-level dropdown called "VistA interfaces"

---

Visual/datatable/css/dataTables.searchHighlight.css
Visual/datatable/js/dataTables.searchHighlight.min.js
Visual/datatable/js/jquery.highlight.js

See: https://issues.osehra.org/browse/VIVIAN-240

Add DataTables SearchHightlight plug-in files

---

Visual/bff_demo.php
Visual/css/vivian.css
Visual/d3.treeview.js
Visual/vivian_osehra_image.php
Visual/vivian_tree_layout_common.js

Add the "Unfulfilled Requirements" display to the OSEHRA ViViaN master branch
Requires the scripts to generate the back-end information found here:  http://review.code.osehra.org/#/c/915/

Add requirements display

---

Visual/Documentation/GenerateData.rst

Update documentation to include changes from:
http://review.code.osehra.org/902
http://review.code.osehra.org/903
http://review.code.osehra.org/904

Update ViViaN data generation document

---

Visual/Documentation/README.rst
Visual/Documentation/UserGuide.rst

ViViaN User Guide

---

Visual/d3.treeview.js
Visual/vista_menus.php

Update the Menus display of ViViaN to read in the JSON information from
a Menu JSON which transports the information in the "_children" attribute
instead of the children.  This will prevent all possible children from
being rendered first which will speed up the load of the page.

Update ViViaN menu display

---

Visual/vivian_osehra_image.php

Remove the code.osehra.org paths from the links in the interface file
menu.
OSEHRA-Id: https://issues.osehra.org/browse/VIVIAN-230

Fix hard-coded links to interface files

---

Visual/vista_menus.php

Fix the capitalization of the directory where the menus are stored to
match the capitalization in the generating scripts.

Fix capitalization of "Menus" directory

---

Visual/package_dep_graph.php

See https://issues.osehra.org/browse/VIVIAN-237

Package Dependency Graph: Filter by group

---

Visual/bff_demo.php
Visual/test/test_bff_demo.py

See https://issues.osehra.org/browse/VIVIAN-339
Note: This test will fail on code.osehra.org, must be tested on a local instance.

Fix bff_demo filtering test

---

Visual/Documentation/testing.rst
Visual/test/test_bff_demo.py
Visual/test/test_index.py
Visual/test/test_installdep.py
Visual/test/test_links.py
Visual/test/test_menus.py
Visual/test/test_pkg_dependency.py
Visual/test/test_pkg_dependency_chart.py

See https://issues.osehra.org/browse/VIVIAN-339

Update ViViaN tests to work with current code

---

Visual/vista_pkg_dep_chart.php

See https://issues.osehra.org/browse/VIVIAN-339 and
https://issues.osehra.org/browse/VIVIAN-342

Remove broken Package Dependency Stats chart

---

Visual/scripts/install_autocomplete_gen.py
Visual/scripts/menu_autocomplete_gen.py
Visual/scripts/option_autocomplete_gen.py
Visual/scripts/package_categories_gen.py
Visual/scripts/pkg_interface_gen.py
Visual/scripts/pkgcsv_to_json.py
Visual/scripts/setup.py

https://issues.osehra.org/browse/VIVIAN-379

Add missing license headers to python files

---

Visual/test/test_pkg_dependency_chart.py
Visual/vista_pkg_dep_chart.php

https://issues.osehra.org/browse/VIVIAN-342
Data generation changes: http://review.code.osehra.org/#/c/1118/

Re-enable Stats bar chart and tests

---

Visual/vista_menus.php

By adding a query to the page of the menu display, we can automatically
select the first option of the value passed as a "name=" query.
See the change here for a properly formatted link:
http://review.code.osehra.org/#/c/1122/

Add direct linking of a menu option

---

Visual/test/test_installdep.py
Visual/test/test_installscale.py
Visual/test/test_links.py
Visual/vivian_osehra_image.php

1. "Join working group" was moved out of nav bar to a button
2. Reimplement some changes from PR #71 that were incorrectly removed
as part of PR #75

Fix link tests

---

Visual/d3.treeview.js
Visual/patchDependency.php
Visual/test/test_installdep.py

Additions to #83 to shrink header, get the test passing, and make the autocomplete boxes functional upon page load

Patch install updates

---

Visual/test/test_dox.py

See https://issues.osehra.org/browse/VIVIAN-328
Requires https://github.com/OSEHRA/VistA/pull/48

First pass at adding DOX tests

---

Visual/vivian_osehra_image.php

Ensure that all links and loaded content used HTTPS as the protocol.

Remove content and link with HTTP

---

Visual/installScale.php
Visual/install_scale.css
Visual/test/test_installscale.py

Enhance the current installScale display with the brush control setup
from the Synthetic Patient Visualization.  Ensure the testing can handle
the new format.

Add Brush control from Synthea Viz to Install scale

---

Visual/index.php

A combination of commits to:
Expand description information in the modal window
Only show the categories that have information in the modal window

Expand modal information 

---

Visual/Documentation/GenerateData.rst

https://issues.osehra.org/browse/VIVIAN-449

Fix link in Generate Data document

---

Visual/Documentation/UserGuide.rst

https://issues.osehra.org/browse/VIVIAN-440

Update ViViaN User Guide

---

Visual/Documentation/howToSubmit.rst

https://issues.osehra.org/browse/VIVIAN-165

Update 'How to Contribute' document

---

Visual/scripts/check_him_data.py

See https://issues.osehra.org/browse/VIVIAN-474

 Convert check_him_data to Python 3 

---

Visual/scripts/check_him_data.py

Script currently fails when using FireFox

Make Chrome the default option for 'check_him_data'

---

Visual/PackageCategories.json
Visual/scripts/BFFExcel2Json.py
Visual/scripts/install_autocomplete_gen.py
Visual/scripts/pkgcsv_to_json.py
Visual/scripts/setup.py

* Removed unicode characters from PackageCategories.json
* Removed unused test output
https://issues.osehra.org/browse/VIVIAN-474

Make setup.py and related scripts Python 3 compatible

---

Visual/test/selenium_utils.py
Visual/test/test_about.py
Visual/test/test_dox.py
Visual/test/test_index.py
Visual/test/test_installdep.py
Visual/test/test_installscale.py
Visual/test/test_menus.py
Visual/test/test_pkg_dependency.py
Visual/test/test_pkg_dependency_chart.py
Visual/test/test_upload.py

https://issues.osehra.org/browse/VIVIAN-474

Ensure tests pass with most recent version of ViViaN on code.osehra.org

---

Visual/Documentation/testing.rst

https://issues.osehra.org/browse/VIVIAN-501

Update documentation to show that Python 2 and 3 are supported

---

Visual/bff_demo.php
Visual/index.php
Visual/installScale.php
Visual/package_dep_graph.php
Visual/patchDependency.php
Visual/vista_menus.php
Visual/vista_pkg_dep.php
Visual/vista_pkg_dep_chart.php
Visual/vivian_osehra_image.php

https://issues.osehra.org/browse/VIVIAN-517

Rename 'files' to 'vivian-data'

---

Visual/patchDependency.php

Remove extra "(" found when setting tooltip content.
Add extra testting of "vivianDataPath" to set value for lower "script"
object.

Fix Javascript in patchDependency.php

---

Visual/bff_demo.php
Visual/index.php
Visual/installScale.php
Visual/patchDependency.php
Visual/vista_pkg_dep.php
Visual/vivian_common_header.php

Continued adding the JQueryUI tool tip to almost every other ViViaN
page.  The HighCharts page is the only one to not transition.

Spread JQuery UI tooltip to other pages

---

Visual/patchDependency.php

Reintroduce the HTML elements needed to create the two links for the
INSTALL and BUILD information for each patch.

Reintroduce modal window

---

Visual/bff_demo.php
Visual/index.php
Visual/installScale.php
Visual/package_dep_graph.php
Visual/pathData.js
Visual/queryVis_stats.php
Visual/scripts/setup.py
Visual/vista_menus.php
Visual/vista_pkg_dep.php
Visual/vista_pkg_dep_chart.php
Visual/vivian_osehra_image.php

Add a new file, created during the run of setup.py, which contains the
relative paths between the files directory and the DOX directory.
This **should** be the same relative path from the vivian html files to
each respective folder.

Add DOX and files URL data

---

Visual/test/test_about.py
Visual/test/test_icrtable.py
Visual/test/test_index.py
Visual/test/test_installscale.py
Visual/test/test_links.py

https://issues.osehra.org/browse/VIVIAN-520

Update tests to work with new directory structure

---

Visual/bff_demo.php
Visual/installScale.php
Visual/patchDependency.php
Visual/vista_pkg_dep_chart.php
Visual/vivian_osehra_image.php

Fix additional places where the hard-coded "../dox" and "../vivian-data"
were not moved to the DOX_URL and FILES_URL.

Fix missed conversions from hard-coded paths

---

Visual/test/test_dox.py
Visual/test/test_index.py
Visual/test/test_links.py
Visual/test/test_upload.py
Visual/test/vivian_test_utils.py

Also, for dox tests, ensure page actually exists.
https://issues.osehra.org/browse/VIVIAN-528
https://issues.osehra.org/browse/VIVIAN-529

Don't use os.path functions for URLs

---

Visual/bff_demo.php
Visual/index.php
Visual/installScale.php
Visual/package_dep_graph.php
Visual/patchDependency.php
Visual/queryVis_stats.php
Visual/vista_menus.php
Visual/vista_pkg_dep.php
Visual/vista_pkg_dep_chart.php
Visual/vivian_common.php
Visual/vivian_header.php

* Rename 'vivian_common_header.php' to 'vivian_common.php'
* Rename 'vivian_osehra_image.php' to 'vivian_header.php'
https://issues.osehra.org/browse/VIVIAN-530

Move common includes into vivian_common.php
