Visual/himData.json
Fix the spelling of the VistALink package, from VistaLink, so that the
HIM link for that package is displayed when the modal window is shown.
=> Fix spelling in himData.json

Visual/Documentation/GenerateData.rst
The "Install" file information is contained in the 9.7 file, not 9.779.  Eliminate the extra numbers
=> Remove Extra numbers from GenerateData.rst

Visual/bff_demo.php, Visual/index.php, Visual/vivian_osehra_image.php
Due to the update from JQuery 1.10.4 to 1.11.0, the array argument
for modal window positioning, ie "['center','center']" is no longer placing
the window correctly.  Remove the values and accept the default which
will put the window in the center of the screen for all instances.
OSEHRA-Id: http://issues.osehra.org/browse/VIVIAN-160
=> Remove position arguments from modal window

Visual/d3.treeview.js
This fixed a bug where clicking on a package value in the install dependency visualization caused the window with the install entry to be opened twice.
=> Removed unnecessary 'openLink' function

Visual/test/test_index.py, Visual/test/test_pkg_dependency.py, Visual/vista_menus.php, Visual/vista_pkg_dep.php, Visual/vista_pkg_dep_chart.php, Visual/vivian_osehra_image.php
Each visualization now has it's on script. Switch between the two using the drop-down on the navigation bar.
The tooltips are now aligned correctly on the circle graph.
Updated tests.
=> Split the circle and chart package dependency visualizations

Visual/installScale.php
Change the "stop" string from "year-mon-day" to "mon/day/year" to prevent
an inconsitency in how Javascript parses the date string.
The previous structure caused the new Date object to be 5 hours earlier to
account for GMT:
2016-12-31
Fri Dec 30 2016 19:00:00 GMT-0500 (Eastern Standard Time)
while the new format returns as expected:
12/31/2016
Sat Dec 31 2016 00:00:00 GMT-0500 (Eastern Standard Time)
=> Fix inital stop date to show Dec 31 of current year

Visual/Documentation/GenerateData.rst, Visual/vivian_osehra_image.php
Add text to the information in the "About" dialog which tells when the
information was generated last and with what Git hash of the VistA-M
repository was used.
=> Add text to the "About" dialog about back-end info

Visual/d3.dependencyedgebundling.js
Fix the link generation to also use the dependents information when
generating the links for the chord diagram of the VistA Package Dependency
page.
=> Fix the link generation by the Dependency chord vis

Visual/patchDependency.php
Add an "package" option which will allow the user to select from all
available patches when viewing the dependencies of the patches.
This will let someone who doesn't know the corresponding package to still
find information about the patch.
This patch requires a change to the install_information.json file which is
generated by the following Gerrit patch:
http://review.code.osehra.org/#/c/851/
=> Add "All Patches" option to Patch Dependency

Visual/test/test_menus.py
Remove the usage of the "Core Applications" menu in the autocomplete test
as it is no longer considered a "top level" menu.
=> Remove "Core Applications" from menu test

Visual/vista_menus.php
Only show links to the HTML entry for an install that has a "hasLink"
parameter of 'true'.  When used with
http://review.code.osehra.org/#/c/876/, will prevent links on the
ZZSERVERMENU display from pointing to non-existant files.
OSEHRA-Id: http://issues.osehra.org/browse/VIVIAN-211
=> Remove ZZSERVERMENU links in Menu display

Visual/bff_demo.php
Change the ID for the page description to not be "description".  This was
being overwritten by the attempt to generate the modal window which put
the description in that location instead of correctly in the pop-up
window.
=> Fix BFF Description setting

Visual/bff_demo.php, Visual/d3.treeview.js
Add a purple colored node which will represent an entirely new Requirement
node to the BFF display to differentiate it from a node that was changed
recently.  Update the legend accordingly as well.
Add an additional filter to remove the first level of "children" if they
do not have any new or updated requirements
=> Add node for "New Requirement"

Visual/scripts/option_autocomplete_gen.py
Change the attribute that was used to look for a menu's children.  Due to
the change to the menu system, the files have their children nodes in
"_children" not "children"
This caused the option_autocomplete to duplicate the menu_autocomplete
values.
=> Fix incorrect recursive trigger in Menu Setup

Visual/bff_demo.php, Visual/d3.treeview.js
Switch the color scheme of the unfulfilled requirements page to eliminate
the potential confusion between the purple and dark blue shaded nodes.
=> Change colors of Unfulfilled Requirement nodes

Visual/Documentation/testing.rst, Visual/test/CMakeLists.txt, Visual/test/test_about.py, Visual/test/test_bff_demo.py, Visual/test/test_icrtable.py, Visual/test/test_index.py, Visual/test/test_installdep.py, Visual/test/test_installscale.py, Visual/test/test_links.py, Visual/test/test_menus.py, Visual/test/test_pkg_dependency.py
* Add support for Chrome
* Update tests to work with recent ViViaN features
* Disable image compare (PILLOW) tests (currently fail)
See https://issues.osehra.org/browse/VIVIAN-261
=> Update ViViaN tests

Visual/vivian_osehra_image.php
Add links in the menu bar to reach to the Namespace and Numberspace
listings that are generated by a Python script in the VistA repository
http://review.code.osehra.org/#/c/980/
=> Add links to name and number-space display

Visual/bff_demo.php, Visual/index.php, Visual/installScale.php, Visual/package_dep_graph.php, Visual/patchDependency.php, Visual/vista_menus.php, Visual/vista_pkg_dep.php, Visual/vista_pkg_dep_chart.php
Reconfigure the ViViaN menu bar highlighting to search for the href that
contains the name of the page and then look through the parents for the
object to make active.
=> Rework menu highlighting to use filename

Visual/bff_demo.php, Visual/vista_menus.php
Ensure that both the Menu display and the name of the requirements JSON
file are correctly capitalized to match what is being generated by the
OSEHRA Python scripts
Capitalization of menus:
https://github.com/OSEHRA/VistA/commit/3d1aa9314d615cc1cf7bc8ed89a1aea8e1eced37#diff-de0b36ffed5ec1bfd7713aae07ebed20R393
Capitalization of requirements:
https://github.com/OSEHRA/VistA/blob/master/Utilities/Dox/PythonScripts/RequirementsParser.py#L45
=> Fix capitalization in ViViaN paths

Visual/bff_demo.php
Add a tooltip to the nodes which show the same information as the
coloring of the node. It should show the name, the type of requirement,
and the date of update of the requirement
OSHERA-Id: https://issues.osehra.org/browse/VIVIAN-338
=> Add tooltip to requirements nodes

Visual/test/test_menus.py
Expand the test capability to cover the Protocol menus side of the
ViViaN menu display.
Also, test the direct linking of both pages by adding the "?name=" to
the URL and ensuring the root node matches the desired text.
=> Expand menu tests to cover Protocol menus

Visual/d3.treeview.js, Visual/patchDependency.php
Add the capability for the install dependency tree to recognize when a
patch has been found in a "layer" above it.  When it does, change the
node to be red and shaped like a diamond to highlight the duplication
=> Add visualization cues for duplicate Install nodes

Visual/index.php
To account for a "deeper" tree with the updated PackageCategories.json
file, widen the display to allow for more layers of the tree to be
shown.
=> Widen display on index.php

Visual/d3.dependencyedgebundling.js, Visual/vista_pkg_dep.php
In PR#94, this case wasn't handled correctly and caused some non-packages (i.e. 'Provide Dentistry') to appear on circle graph as if they were packages.
https://issues.osehra.org/browse/VIVIAN-451
=> Handle groups whose only child has 'primary_function' set to No

Visual/queryVis_stats.php
Fix the parsing of the multiple to do a better job checking for the
object's data.  Ensure that the regex is case-insensitive so that the
"PERSON CLASS" field will be found when the field is "Person Class"
Also, add any trailing "S" on a name to be option, as "KEYS" has the
data in a field called "KEY"
=> Fix parsing of multiples in Classify Data

Visual/queryVis_stats.php
Match the datatables usage of the VistA FileManGlobalDataParser in the
display found in the queryViz.  Ensure that the columns are shrunk to
prevent the table from scrolling off the edge of the page in a PDF.
=> Match DataTables usage in ViViaN

Visual/patchDependency.php, Visual/style.css, Visual/vista_menus.php, Visual/vivian_common_header.php
instead of creating our own tooltip, use the JQuery UI tooltip to
smartly interact with the edge of the screen.
Start using this tooltip on the pages that allow panning and zooming, the two menu options pages and the install dependency page
=> Switch to using JQueryUI tooltip
